# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 63d73e4a8480629fbbafcbb3df1bb541a12cbb0a9f66bda6b62bd9a0fb98ad0d09527a0e5757763d1c97c040afbc91512c241ebb8336e632a3a66f774f72ea2f

test:
  secret_key_base: 80fc65a4ee67d39112a3b2c0e67f1cb6bc03d186d10c73ecf75952574d2574a3d431a0372c7b5952d94077fbf40238903c6fa3455cfa622f6cf6aaee2414e2fa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
